### ISSUE TITLE
AttributeError: module 'urllib' has no attribute 'error'

### ISSUE THREAD

**Issue by yingbo** [druid-io/pydruid#228]
I got this error:

AttributeError: module 'urllib' has no attribute 'error'

I think in the client.py we should `import urllib.request` other than `import urllib`, in python 3.7 and python 3.8 at least, but I'm not sure how to fix it to make it works on all python versions.

**Comment by eden-wang** [comment]
I encountered the same problem in python 3.6.9, mac

**Comment by eden-wang** [comment]
wired, I created another venv, and it works now...

**Comment by yingbo** [comment]
@eden-wang You can check the client.py file to see what it's importing. I'm not sure starting which python 3 version, it requires to `import urllib.request `

**Comment by eden-wang** [comment]
> @eden-wang You can check the client.py file to see what it's importing. I'm not sure starting which python 3 version, it requires to `import urllib.request `

It is `import urllib.request`

**Comment by yingbo** [comment]
Just checked it's still `import urllib`: https://github.com/druid-io/pydruid/blob/master/pydruid/client.py

**Comment by sub007** [comment]
I requires import `urllib.error` to be imported explicitly.

**Comment by yingbo** [comment]
Looks this issue was fixed already. I'll close this.

**Comment by lokkju** [comment]
`client.py` still seems to have `import urllib`; where do you see it as fixed?

**Comment by yingbo** [comment]
Hi @lokkju ,
From their latest release: https://github.com/druid-io/pydruid/blob/pydruid-0.5.2/pydruid/client.py#L22, you can see 
`from six.moves import urllib`. The `six.moves` fixed the problem

**Comment by sub007** [comment]
@yingbo : The code you are referring to is 0.5.2.
Isn't master or 0.6 the latest release? They both have `import urllib`
https://github.com/druid-io/pydruid/blob/master/pydruid/client.py#L18

**Comment by yingbo** [comment]
Hi @sub007 , you are right that I was referencing and older version above. For the current version or master, looks they changed to user `urllib.request` in the codes already: https://github.com/druid-io/pydruid/blob/498efcab0e4b64175bbaa4c1157b1216eca6c2e0/pydruid/client.py#L42. I am using python 3.7 or 3.8 mainly and didn't see any error. I am, however, not sure whether it will work on python 2.7.

**Comment by jccardonar** [comment]
I experienced this and fixed it by explicitly adding urllib.error (then later urllib.request) to client.py (thanks @sub007 ).

However, it was funny that running the script in ipython did not raise any exceptions. Anybody knows why?

**Comment by yingbo** [comment]
I have no idea either how the problem was fixed, or even being fixed. Hope the pydruid team can give us an answer.

**Comment by gitmstoute** [comment]
I encoutered this error as well! Per the others, adding:

`import urllib.error
import urllib.request
`
To site-packages/pydruid/client.py of my virtualenv resolved the issue.

**Comment by daymos** [comment]
It was fixed in versin 5.2. However is broken again in 6.* I managed to run this by installing 5.2.
However this is an odd one, as I only had the problem while running it inside a docker container. Locally 6.* works alright.

**Comment by Mihaylov93** [comment]
Looks like with Python 3.9.10 `pydruid==0.6.2`, `urllib3==1.26.12` the `AttributeError: module 'urllib' has no attribute 'error'` isn't produced anymore for me.

**Comment by al-one-zero** [comment]
Looks like I still have this issue with the 3.11 CPython interpreter and pydruid 6.5. What's interesting is that I don't have this issue when using IPython.

**Comment by matkalinowski** [comment]
This issue still occurs for versions:
Python 3.10.7
- pydruid==0.6.5
- urllib3==2.0.3

Explicitly importing urllib.request in script solves it.
