### ISSUE TITLE
Pydruid Breaks on latest Python version

### ISSUE THREAD

**Issue by vvagias** [druid-io/pydruid#241]
`Traceback (most recent call last):
  File "main.py", line 2, in <module>
    from pydruid.client import *
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/pydruid/client.py", line 21, in <module>
    from pydruid.query import QueryBuilder
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/pydruid/query.py", line 28, in <module>
    class Query(collections.abc.MutableSequence):
  File "/usr/lib/python3.8/collections/__init__.py", line 55, in __getattr__
    raise AttributeError(f'module {__name__!r} has no attribute {name!r}')
AttributeError: module 'collections' has no attribute 'abc'`

This is happening for Python 3.8.2 , last version that works fine is 3.7.6 but this is not a possible solution for repl.it 

Looking at the release notes it is how abc is being imported needs to be collections.abc

**Comment by betodealmeida** [comment]
Pydruid is now working with 3.8. We should add support for 3.9+ though.
